# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db0bf8fc79bd7bfa8dd2c8a8654b8a56bd51e5442626b297a480c6e455aedcf8ab0aacc603201c27614581043a81b04b44a77d53cf0a95d384760e1d2e4bf68f

test:
  secret_key_base: 80472270dac0c538c3db0aef74197d02f29a3b87f8c06a0b01a8e369bf0f874a463a5a4349b1fd6d4ec661d1e0c344e57b17c42eae9076d8789efb448ec5346a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
